// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPages.Data;

namespace RazorPages.Migrations
{
    [DbContext(typeof(RazorPagesContext))]
    [Migration("20200518160749_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorPages.Models.MediaDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Altele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataCreare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evenimente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locuri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Moved")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peisaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Persoane")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaDTO");
                });
#pragma warning restore 612, 618
        }
    }
}
